name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: determine_release_tag
        run: |
          if [[ $GITHUB_REF = refs/tags/* ]]; then
            tag="${GITHUB_REF#refs/tags/}"
          else
            tag="$(git describe --tags --abbrev=0)"
          fi
          echo "TAG=$tag" >> "$GITHUB_OUTPUT"
          echo $tag
      - name: determine_release_title_prefix
        run: |
          prefix="${GITHUB_REPOSITORY#*/}"
          echo "PREFIX=$prefix" >> "$GITHUB_OUTPUT"
          echo $prefix
      - name: validate tags
        run: |
          echo ${{ TAG }}
          echo ${{ PREFIX }}
      - run: ./.github/workflows/build_and_release.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          GH_RELEASE_TAG: ${{ steps.determine_release_tag.outputs.TAG }}
          GH_RELEASE_TITLE_PREFIX: ${{ steps.determine_release_title_prefix.outputs.PREFIX }}
        shell: bash
